### ISSUE TITLE
[BUG]Cannot see monitoring data for MySQL and HTTP requests.

### ISSUE THREAD

**Issue by asasas234** [pixie-io/pixie#1341]
**Describe the bug**
I deployed a test application and accessed one of its http interfaces through the company’s office network. The application just checked mysql and the interface could be accessed normally, but I couldn’t see any requests for this http interface or mysql monitoring information in Pixie. The access to the interface was routed through a loadbalance type service via DNS.

**Expected behavior**
I should be able to see the relevant HTTP and MySQL monitoring information.

**App information (please complete the following information):**
- Pixie version
- 
- K8s cluster version
- 1.22
- Node Kernel version
- 5.10.134-13.al8.x86_64
- Browser version
- chrome  113.0.5672.92（正式版本） (arm64)

<details>
<summary>Details</summary>

</details>

**Comment by asasas234** [comment]
I found that I can monitor the http call by way of curl access to the target serviceName in a Pod inside the k8s cluster, but from outside the cluster, through the domain name pointing to the service inside my cluster, the type is loadbalancer, such a way is not monitored, I want to know why this is? Is this normal?

**Comment by ddelnano** [comment]
Hi @asasas234, can you provide more information about the applications running on the cluster and the type of loadbalancer in use? What language is the http service written in and is it connecting to the MySQL database over TLS? Is the loadbalancer connecting to the HTTP service over TLS as well?

**Comment by asasas234** [comment]
@ddelnano I'm using the HTTP protocol and not connecting to MySQL via TLS. My backend web service is written in Java language, and I can monitor it through serviceName by using curl from other pods. However, when I access the service (which is of type loadbalancer) within the cluster through the domain name pointing to the service inside the cluster, I cannot monitor it (neither the HTTP requests nor the MySQL requests).

**Comment by asasas234** [comment]
'''
Below is the YAML configuration for my service.
```
apiVersion: v1
kind: Service
metadata:
  name: xxxx
  namespace: xxx
  labels:
    app: xxx
    cloud: ali
    cluster: xxx
    service.beta.kubernetes.io/hash: f55f3cf32b8ef65bdc5184968c33b2785024f9a4f16a73306907f4e9
    service.k8s.alibaba/loadbalancer-id: lb-t4nlefwto04c1a4436i8o
  annotations:
    AnnotationCluster: '40'
    AnnotationLoadBalanceURL: http://ratel.vipkid.com.cn/v1/api/services/updateLBIp
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-protocol-port: http:80
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-scheduler: wrr
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/backend-type: eni
spec:
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30430
    - name: crontab
      protocol: TCP
      port: 50091
      targetPort: 50091
      nodePort: 31010
  selector:
    app: xxxx
    build_id: 'xxx'
    runenv: prod
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local
  healthCheckNodePort: 32035
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
```
