### ISSUE TITLE
Air Gapped installation still trying to reach external internet resources

### ISSUE THREAD

**Issue by gofrolist** [pixie-io/pixie#1838]
**Describe the bug**
Air Gapped installation still trying to reach external internet resources.

**To Reproduce**
Install Air Gapped Proxy Cloud following official documentation https://docs.px.dev/installing-pixie/install-guides/airgap-pixie/#deploy-pixie-cloud
Check the logs of pods `api-server` and `scriptmgr-server`

**Expected behavior**
`api-server` and `scriptmgr-server` should download bundle from internal resource and this should be configured via configmap `pl-script-bundles-config` and `pl-scriptmgr-config`

**Logs**

`api-server`
```
time="2024-02-14T00:35:38Z" level=error msg="Error checking bundle file URL" error="Get \"https://storage.googleapis.com/pixie-prod-artifacts/script-bundles/bundle-core.json\": dial tcp 142.250.72.187:443: i/o timeout"
time="2024-02-14T00:35:38Z" level=error msg="Error checking bundle file URL" error="Get \"https://artifacts.px.dev/pxl_scripts/bundle.json\": dial tcp 185.199.111.153:443: i/o timeout"
```

`scriptmgr-server`
```
time="2024-02-14T00:29:10Z" level=error msg="Failed to update store using bundle.json from gcs." bucket=pixie-prod-artifacts error="rpc error: code = Internal desc = failed to download bundle.json" path=script-bundles/bundle-oss.json
time="2024-02-14T00:30:40Z" level=error msg="Failed to get attrs of bundle.json" bucket=pixie-prod-artifacts error="Get \"https://storage.googleapis.com/storage/v1/b/pixie-prod-artifacts/o/script-bundles%2Fbundle-oss.json?alt=json&prettyPrint=false&projection=full\": dial tcp 142.250.176.27:443: i/o timeout" path=script-bundles/bundle-oss.json
```

`kubectl -n plc get configmaps pl-script-bundles-config -o yaml`

```
apiVersion: v1
data:
  SCRIPT_BUNDLE_DEV: "false"
  SCRIPT_BUNDLE_URLS: '[ "https://<MY_INTERNAL_DOMAIN>/artifactory/pxl_scripts/bundle-oss.json" ]'
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-script-bundles-config
  namespace: plc
```

`kubectl -n plc get configmaps pl-scriptmgr-config -o yaml`
```
apiVersion: v1
data:
  PL_BUNDLE_BUCKET: pixie-prod-artifacts
  PL_BUNDLE_PATH: script-bundles/bundle-oss.json
kind: ConfigMap
metadata:
  labels:
    app: pl-cloud
  name: pl-scriptmgr-config
  namespace: plc
```

**App information (please complete the following information):**
- Pixie version:  1.0.7 `Built 2023.07.12.09.19` 
- K8s cluster version: 1.21.5
- Node Kernel version: 5.4.17-2136.309.5.el7uek.x86_64
- Browser version: Chrome 121.0.6167.160 (Official Build) (arm64)
