### ISSUE TITLE
deploy self-hosted pixie-cloud failed follow the production-readiness

### ISSUE THREAD

**Issue by Pger-Y** [pixie-io/pixie#2202]
**Describe the bug**
I'm encountering an issue while trying to deploy a self-hosted Pixie Cloud for a production environment by following the official guide: [Production Readiness Guide](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/production-readiness/).

The guide states:

If you are using the [Self-Hosted installation](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/),

Follow steps 1 - 5 and 8 in [Deploy Pixie Cloud](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#1.-deploy-pixie-cloud).
Comment lines 94 to 106 in ./scripts/create_cloud_secrets.sh
Execute the script as explained in step 9 of [Deploy Pixie Cloud](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#1.-deploy-pixie-cloud)

Initial Problem with Script Lines:
I found that the line numbers (94-106) referenced for commenting out in ./scripts/create_cloud_secrets.sh appear to be outdated in the current version of the script. I attempted to identify the correct corresponding lines by referencing an older tag of the script and commented out lines 96-108, which seemed to match the intended section for generating self-signed certs (which I intended to replace with my own).

Subsequent Issue with Custom Certificate and Internal Access:
Since commenting out those lines would prevent the creation of the cloud-proxy-tls-certs secret, I manually created this secret using our own wildcard certificate (*.zhipuai-infra.cn, which correctly covers pixie.xxx.xxx).

When I access https://pixie.xxx.xxx (where xxx.xxx is my domain, correctly covered by the wildcard cert) through my Traefik Ingress, the external access seems to work up to a point, but I encounter an "Internal Server Error" from Pixie.

To investigate, I tried to curl the internal cloud-proxy-service (which is a LoadBalancer type service, IP 10.123.60.98 in my setup). This internal request fails with the following TLS error:

* start date: Oct 15 00:00:00 2024 GMT
* expire date: Oct 15 23:59:59 2025 GMT
* subjectAltName does not match ipv4 address 10.123.60.98
* SSL: no alternative certificate subject name matches target ipv4 address '10.123.60.98'
* Closing connection
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target ipv4 address '10.123.60.98'
More details here: https://curl.se/docs/sslcerts.html
This error suggests that the certificate being presented by the cloud-proxy pod/service at IP 10.123.60.98 (which is using the cloud-proxy-tls-certs secret I provided) does not have 10.123.60.98 or an appropriate internal DNS name as a Subject Alternative Name (SAN). My wildcard certificate is intended for external hostnames (like pixie.xxx.xxx) and naturally does not include internal IP addresses or Kubernetes service names (like cloud-proxy-service.namespace.svc.cluster.local) in its SANs.

My Current Understanding/Question:
It seems the cloud-proxy might be using the cloud-proxy-tls-certs for two purposes:

TLS termination for external traffic coming via Ingress (for pixie.xxx.xxx).
Possibly for internal communication or health checks that are trying to access it via its internal IP or service name, leading to the SAN mismatch.
Could you please provide guidance on:

The correct lines to comment out in create_cloud_secrets.sh for the latest version if one intends to use their own external-facing TLS certificates?
How TLS is intended to be handled for internal access to cloud-proxy or between internal Pixie Cloud components if the cloud-proxy-tls-certs secret is configured with a public-facing wildcard certificate? Should there be a separate internal CA and certificates for such internal traffic, or should the cloud-proxy-tls-certs also include SANs for internal service names/IPs?
Additional Context:

I am using Traefik as my Ingress controller, not Nginx. I have modified the Ingress YAML accordingly.
My traffic flow is: Client -> Load Balancer (External) -> Traefik Pod (TLS termination for pixie.xxx.xxx using my wildcard cert) -> Ingress Route -> cloud-proxy-service (K8s Service of type LoadBalancer, exposing cloud-proxy pods) -> cloud-proxy pod (IP 10.123.60.98).
Correction based on flow: It's possible Traefik is not terminating TLS and is passing it through to the cloud-proxy-service if the Ingress is configured for TLS passthrough, or if Traefik is terminating, then the communication from Traefik to cloud-proxy-service might be HTTP or attempting HTTPS with this cert mismatch. My current setup has Traefik handling TLS for pixie.xxx.xxx.
Thanks for your help!
<img width="1093" alt="Image" src="https://github.com/user-attachments/assets/7e8e0cbf-a928-44b2-823f-6e7247fc6669" />

ingress yaml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-ingress-https
  namespace: plc
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: "https"
    # traefik.ingress.kubernetes.io/service.serverstransport: "insecure@kubernetescrd"
spec:
  tls:
    - hosts:
        - pixie.xxx.com
        - work-pixie.xxx.com
  rules:
    - host: pixie.xxx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-proxy-service
                port:
                  number: 443
    - host: work-pixie.xxx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-proxy-service
                port:
                  number: 443

```

**To Reproduce**

**Expected behavior**
deploy self-hosted pixie-cloud successfully

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Logs**
i'm deploy pixie cloud

**App information (please complete the following information):**
- Pixie version  release/cloud/v0.1.9
- K8s cluster version v1.31.1

**Additional context**
