### ISSUE TITLE
Enable all Pixie components to be patched via Helm chart

### ISSUE THREAD

**Issue by bpschmitt** [pixie-io/pixie#382]
**Is your feature request related to a problem? Please describe.**

I need to ensure certain Pixie components run on specific nodes in my cluster.  

Currently, I'm able to patch the following via the `pixie-operator` chart:

- kelvin
- vizier-query-broker
- vizier-cloud-connector
 - pl-nats
 - vizier-metadata
 
 Example:
 
 ```
   patches:
    kelvin: '{"spec": {"template": {"spec": { "nodeSelector": {"pixie.io/components": "true" }}}}}'
    vizier-query-broker: '{"spec": {"template": {"spec": { "nodeSelector": {"pixie.io/components": "true" }}}}}'
    vizier-cloud-connector: '{"spec": {"template": {"spec": { "nodeSelector": {"pixie.io/components": "true" }}}}}'
    pl-nats: '{"spec": {"template": {"spec": { "nodeSelector": {"pixie.io/components": "true" }}}}}'
    vizier-metadata: '{"spec": {"template": {"spec": { "nodeSelector": {"pixie.io/components": "true" }}}}}
 ```
 
 However, I _can't_ patch the following via Helm:
 
 - catalog-operator
 - olm-operator
 - vizier-operator

**Describe the solution you'd like**

Provide the ability to patch _all_ deployed resources, not just the Vizier resources:

```
# A set of custom patches to apply to the deployed Vizier resources.
# The key should be the name of the resource to apply the patch to, and the value is the patch to apply.
# Currently, only a JSON format is accepted, such as:
# `{"spec": {"template": {"spec": { "tolerations": [{"key": "test", "operator": "Exists", "effect": "NoExecute" }]}}}}`
patches: {}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
