### ISSUE TITLE
[Self-hosted Pixie on non-minikube cluster] Login error "server closed the stream without sending trailers"

### ISSUE THREAD

**Issue by amirkkn** [pixie-io/pixie#602]
**Describe the bug**
I've deployed pixie based on your [install documentation](https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/) to our self-hosted kubernetes . it is about real cluster and not minikube. Because of our internal policy we don't use loadbalancer service. Therefore I replaced it with local service and using nginx ingress for exposing it to outside. The current state is you can see GUI and login with admin user. For deploying pixie, i need to login to server: 

```
px auth login
```

But it throws the error (pls see screenshot). If i set the "local_mode=true" to login endpoint, it generates a token, but this token doesn't work and i get that error again:

```
Pixie CLI
*******************************
* ENV VARS
* 	 PL_CLOUD_ADDR=plc.e2e.example.net
*******************************
Starting browser... (if browser-based login fails, try running `px auth login --manual` for headless login)
Fetching refresh token ...
Failed to perform browser based auth. Will try manual auth error=rpc error: code = Internal desc = server closed the stream without sending trailers

Please Visit:
 	 https://work.plc.e2e.example.net:443/login?local_mode=true

Copy and paste token here:
FATA[0059] Failed to login                               error="rpc error: code = Internal desc = server closed the stream without sending trailers"

FAILED to authenticate with Pixie cloud.

```

For other attempt i pass the API key which i created with admin user via GUI, but it doesn't work as well:
``` 
px auth login --api_key <key>
Pixie CLI
*******************************
* ENV VARS
* 	 PL_CLOUD_ADDR=plc.e2e.example.net
*******************************
FATA[0008] Failed to login                               error="rpc error: code = Internal desc = server closed the stream without sending trailers"
```

Could you please give some hints to resolve this issue?

**Screenshots**
<img width="783" alt="image" src="https://user-images.githubusercontent.com/22954158/192250322-ebeefcde-b1be-4d4b-b5ef-7c16669d9163.png">

**App information (please complete the following information):**
- Pixie version - v0.7.17
- K8s cluster version - 1.23

**Comment by zasgar** [comment]
@aimichelle, can you try to reproduce this and help out?

**Comment by aimichelle** [comment]
Hi @amirkkn , would you mind sharing your nginx ingress configurations? My guess is there is some misconfiguration there.

**Comment by amirkkn** [comment]
Hi @aimichelle ,

here is my nginx  ingress config:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: plc-ingress
  namespace: plc
spec:
  ingressClassName: nginx-intranet
  rules:
  - host: work.plc.e2e.example.net
    http:
      paths:
      - backend:
          service:
            name: cloud-proxy-service
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
  - host: plc.e2e.example.net
    http:
      paths:
      - backend:
          service:
            name: cloud-proxy-service
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - '*.plc.e2e.example.net'
    - work.plc.e2e.example.net
    secretName: plc-ingress-ssl
```
