### ISSUE TITLE
Can't install pixie in an air gapped environment

### ISSUE THREAD

**Issue by dragonTour** [pixie-io/pixie#665]
**Describe the bug**
The vizier-cloud-connector deployMent created pod vizier-pem to connect to the pl-nats service has SSL authentication problems

**To Reproduce**
Currently I'm trying to install it via [artifacts](https://storage.googleapis.com/pixie-dev-public/vizier/latest/vizier_yamls.tar).

**Logs**
```
[root@iZbp19b1d0ucqjsqsmh917Z ssl]# kubectl get po -n pl
NAME                                     READY   STATUS             RESTARTS      AGE
kelvin-66f686cbdd-rprsl                  0/1     CrashLoopBackOff   5 (92s ago)   5m53s
pl-nats-0                                1/1     Running            0             5m49s
vizier-cloud-connector-7cf8459b8-vngzh   1/1     Running            0             5m53s
vizier-metadata-0                        1/1     Running            0             5m46s
vizier-pem-bcrv2                         0/1     CrashLoopBackOff   4 (83s ago)   5m52s
vizier-pem-d8ght                         0/1     CrashLoopBackOff   4 (59s ago)   5m52s
vizier-pem-g8pkp                         0/1     CrashLoopBackOff   4 (68s ago)   5m50s
vizier-query-broker-bdc44d575-tsqjx      1/1     Running            0             5m53s

[root@iZbp19b1d0ucqjsqsmh917Z ssl]# kubectl logs vizier-pem-bcrv2 -n pl
...
I20221209 07:09:15.829245 2354094 bcc_wrapper.cc:170] Initializing BPF program ...
I20221209 07:09:17.530501 2354094 scoped_timer.h:48] Timer(init_bpf_program) : 1.70 s
I20221209 07:09:17.531980 2354094 perf_profile_connector.cc:145] PerfProfiler: Stack trace profiling sampling probe successfully deployed.
I20221209 07:09:17.532011 2354094 perf_profile_connector.cc:161] PerfProfiler: Java symbolization enabled.
I20221209 07:09:17.532048 2354094 java_symbolizer.cc:242] JavaSymbolizer found agent lib /pl/libpx-java-agent.so.
I20221209 07:09:17.532063 2354094 stirling.cc:433] Adding info class: [perf_profiler/stack_traces.beta]
I20221209 07:09:17.532125 2354094 source_connector.cc:35] Initializing source connector: proc_exit_tracer
I20221209 07:09:17.532145 2354094 linux_headers.cc:90] Obtained Linux version string from `uname`: 4.18.0-348.2.1.el8_5.x86_64
I20221209 07:09:17.532155 2354094 linux_headers.cc:635] Detected kernel release (uname -r): 4.18.0-348.2.1.el8_5.x86_64
I20221209 07:09:17.532198 2354094 bcc_wrapper.cc:121] Using linux headers found at /lib/modules/4.18.0-348.2.1.el8_5.x86_64/build for BCC runtime.
I20221209 07:09:17.532258 2354094 bcc_wrapper.cc:170] Initializing BPF program ...
I20221209 07:09:18.477037 2354094 scoped_timer.h:48] Timer(init_bpf_program) : 944.76 ms
I20221209 07:09:18.488960 2354094 stirling.cc:433] Adding info class: [proc_exit_tracer/proc_exit_events]
I20221209 07:09:18.489020 2354094 source_connector.cc:35] Initializing source connector: stirling_error
I20221209 07:09:18.489096 2354094 stirling.cc:433] Adding info class: [stirling_error/stirling_error]
I20221209 07:09:18.489112 2354094 stirling.cc:433] Adding info class: [stirling_error/probe_status]
I20221209 07:09:18.489173 2354094 stirling.cc:414] Stirling successfully initialized.
I20221209 07:09:18.493793 2354094 manager.cc:156] Hostname: iZbp11uldizj3s4hzhgd73Z
Error: 29 - SSL Error - (conn.c:737): SSL handshake error: 18:self signed certificate:depth=0:cert=/O=*/CN=*:issuer=/O=*/CN=*
Stack: (library version: 3.3.0)
  01 - _makeTLSConn
  02 - _checkForSecure
  03 - _processExpectedInfo
  04 - _processConnInit
  05 - _connect
  06 - natsConnection_Connect
F20221209 07:09:19.833931 2354094 statusor.h:148] Check failed: _s.ok() Bad Status: Unknown : Failed to connect to NATS, nats_status=29
*** Check failure stack trace: ***
E20221209 07:09:19.834019 2354094 signal_action.cc:63] Caught Aborted, suspect faulting address 0x23ebae. Trace:
**************************
...

```

**App information (please complete the following information):**
- Pixie version :
   pixie_cloud: 1667424853
   Pixie : latest
- K8s cluster version v1.23
- go version go1.19.1 linux/amd64

**Comment by dragonTour** [comment]
@aimichelle Thank you for your reply！
The above log certificate was created manually by me after I found that service-tls-certs secret was missing when I created pod。Then I look through the yaml file and find cert-provisioner-job，Reading the source code reveals that it is a job to create a certificate。
Also found a small bug in the yaml file：
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-updater-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-updater-role
subjects:
- kind: ServiceAccount
  name: pl-updater-service-account
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-updater-role
  namespace: pl
rules:
- apiGroups:
...
```

The clusterBinding role above bings a ClusterRole named pl-upater -role,But pl-upater-role is the type of a role.I modified `roleRef.name = pl-upater -cluster-role`。

I created the secrets, configmap and role, rolebing, clusterRole, clusterRoleBinding。Then I create cert-provisioner-job job。
```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: cert-provisioner-job
  namespace: pl
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: pl-monitoring
        component: vizier
        vizier-bootstrap: "true"
      name: cert-provisioner-job
    spec:
      containers:
        - env:
            - name: PL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: pl-cloud-config
            - configMapRef:
                name: pl-cluster-config
                optional: true
          image: gcr.io/pixie-oss/pixie-prod/vizier/cert_provisioner_image:0.12.9
          name: provisioner
      restartPolicy: Never
      serviceAccountName: pl-updater-service-account
```
Please check the log below:
```
[root@iZbp19b1d0ucqjsqsmh917Z yamls]# kubectl apply -f job.yaml 
job.batch/cert-provisioner-job created

[root@iZbp19b1d0ucqjsqsmh917Z yamls]# kubectl get po -n pl
NAME                         READY   STATUS   RESTARTS   AGE
cert-provisioner-job-k9d4b   0/1     Error    0          10s
cert-provisioner-job-sqqwd   0/1     Error    0          8s

[root@iZbp19b1d0ucqjsqsmh917Z yamls]# kubectl logs cert-provisioner-job-k9d4b -n pl
time="2022-12-13T02:39:06Z" level=info msg="Checking if certs already exist..."
time="2022-12-13T02:39:06Z" level=fatal msg="pl-cluster-secrets does not exist"

[root@iZbp19b1d0ucqjsqsmh917Z yamls]# kubectl describe po cert-provisioner-job-sqqwd -n pl
Name:         cert-provisioner-job-sqqwd
Namespace:    pl
Priority:     0
...
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    2m29s                  default-scheduler  Successfully assigned pl/cert-provisioner-job-sqqwd to izbp11uldizj3s4hzhgd74z
  Normal   Pulled       2m29s                  kubelet            Container image "gcr.io/pixie-oss/pixie-prod/vizier/cert_provisioner_image:0.12.9" already present on machine
  Normal   Created      2m28s                  kubelet            Created container provisioner
  Normal   Started      2m28s                  kubelet            Started container provisioner
  Warning  FailedMount  2m26s (x3 over 2m27s)  kubelet            MountVolume.SetUp failed for volume "kube-api-access-k9cgn" : object "pl"/"kube-root-ca.crt" not registered

[root@iZbp19b1d0ucqjsqsmh917Z yamls]# kubectl get secret -n pl
NAME                                     TYPE                                  DATA   AGE
cloud-conn-service-account-token-fgj9l   kubernetes.io/service-account-token   3      17h
default-token-7g6kb                      kubernetes.io/service-account-token   3      17h
metadata-service-account-token-mcvdn     kubernetes.io/service-account-token   3      17h
pl-cluster-secrets                       Opaque                                1      17h
pl-deploy-secrets                        Opaque                                1      17h
pl-updater-service-account-token-mnf88   kubernetes.io/service-account-token   3      17h
```
The jobcreates two Pods，And one of them will produce an error：`MountVolume.SetUp failed for volume "kube-api-access-k9cgn" : object "pl"/"kube-root-ca.crt" not registered`,
And can't `find pl-cluster-secrets`.
