### ISSUE TITLE
Missing data when tracing http 1.1 tls traffic for Go on Container Optimized OS

### ISSUE THREAD

**Issue by ddelnano** [pixie-io/pixie#899]
**Describe the bug**
We recently discovered an issue where Go http 1.1 tls traffic is missing on COS (Container optimized OS). This was reproducible on k8s 1.24 and 1.2X.

**To Reproduce**
1. Add the following to the `src/e2e_test/protocol_loadtest/skaffold_loadtest.yaml`
```
profiles:
- name: go1_19 
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
      - --@io_bazel_rules_go//go/toolchain:sdk_version=1.19
```
2. Run skaffold to deploy the golang load test
```
skaffold run -f src/e2e_test/protocol_loadtest/skaffold_loadtest.yaml
```
3. Port forward 8081 to the pod and curl it
```
curl -X POST -d '{"abcd":1234}' -H 'Content-Type: application/json' -k https://localhost:8081/ -vvv
```
4. Notice that the data is missing in the UI 
This will use go1.20. To try it with go1.19:
add the following to the bottom of skaffold_loadtest.yaml:

**Expected behavior**

The http traffic should be traced.

**App information (please complete the following information):**
- `main` deployment as of Feb 13th
- K8s cluster version: 1.23 and 1.24
- Container Optimized OS

**Additional context**

There is an existing bug for tracing go http 1.1 traffic when a response is gzipped and there is a chunked response (#495). This bug seems to occur even when that is disabled in the load test application mentioned above.
